### ISSUE TITLE
Unify data model

### ISSUE THREAD

**Issue by st3v3nhunt** [nhsuk/sexual-health-service-data-combiner#6]
Remap the service data models so shared properties are the same. Currently this consists of:
* `address` - the GSD services have `address.addressLines` whereas the pharmacy services have `address.line1`, `address.line2`, etc. `postcode` will need to be made consistent too.
* `contacts` - `contacts.telephone` is used on GSD services whereas `contacts.telephoneNumber` is used for pharmacy services.
* The property for specifying service type needs to be consistent. GSD services use `type`, but the raw pharmacy service records is `serviceType` which leads to some mapping code within the combiner to make that `type`. It would easier to just one property across all service types.

Options for unifying within this application or going to the source ETL and making the changes there.

**Comment by beseven** [comment]
Re this: https://confluence.service.nhs.uk/display/TPP/WR2349+-+Persistent+IDs+for+GDOS+profiles - If the data team finish this work, some of these issues might not exist as they will add the GDS data into the Organisation table.
